#!/usr/bin/env python

import os, sys
import serial
import time
################################################################################
r, w = os.pipe()
################################################################################
r = os.fdopen(r) 
print("Read text:", r.read()) 