#!/usr/bin/env python

# import usb.core
# import usb.util

import os, sys
import serial
import time

import os.path
from os import path

import math
import unicornhat as unicorn
from time import sleep
from datetime import datetime
################################################################################
def doSetup():
	global height, width
	unicorn.set_layout(unicorn.HAT)
	unicorn.rotation(0)
	unicorn.brightness(0.5)
	width,height=unicorn.get_shape()
	#####
	r = 255
	b = 0
	g = 0
	#####
	unicorn.set_pixel(0,0,r,g,b)
	unicorn.set_pixel(1,1,r,g,b)
	unicorn.set_pixel(2,2,r,g,b)
	unicorn.set_pixel(3,3,r,g,b)
	unicorn.set_pixel(4,4,r,g,b)
	unicorn.set_pixel(5,5,r,g,b)
	unicorn.set_pixel(6,6,r,g,b)
	unicorn.set_pixel(7,7,r,g,b)
	#####
	unicorn.set_pixel(7,0,r,g,b)
	unicorn.set_pixel(6,1,r,g,b)
	unicorn.set_pixel(5,2,r,g,b)
	unicorn.set_pixel(4,3,r,g,b)
	unicorn.set_pixel(3,4,r,g,b)
	unicorn.set_pixel(2,5,r,g,b)
	unicorn.set_pixel(1,6,r,g,b)
	unicorn.set_pixel(0,7,r,g,b)
################################################################################
if __name__ == '__main__':
	doSetup()
	unicorn.show()
	time.sleep(10)